-- Generated by sqlflow rollup ddl. Do not edit: change the rollups file and
-- regenerate. Run it inside one transaction, which a migration runner opens.

-- Rollup posts, kept from posts_per_minute_by_lang.
-- Blocks the source's writers until commit, so no write lands between the
-- triggers existing and the backfill reading.
LOCK TABLE "posts_per_minute_by_lang" IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE IF NOT EXISTS "posts_by_lang_5m" AS
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."lang" AS "lang",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_by_lang_5m_key"
  ON "posts_by_lang_5m" ("bucket", "lang") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_by_lang_15m" AS
SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."lang" AS "lang",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_by_lang_15m_key"
  ON "posts_by_lang_15m" ("bucket", "lang") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_by_lang_1h" AS
SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."lang" AS "lang",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_by_lang_1h_key"
  ON "posts_by_lang_1h" ("bucket", "lang") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_by_lang_6h" AS
SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."lang" AS "lang",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_by_lang_6h_key"
  ON "posts_by_lang_6h" ("bucket", "lang") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_by_lang_1d" AS
SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."lang" AS "lang",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_by_lang_1d_key"
  ON "posts_by_lang_1d" ("bucket", "lang") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_total_5m" AS
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       count(DISTINCT f."bucket") AS "minutes",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_total_5m_key"
  ON "posts_total_5m" ("bucket") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_total_15m" AS
SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       count(DISTINCT f."bucket") AS "minutes",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_total_15m_key"
  ON "posts_total_15m" ("bucket") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_total_1h" AS
SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       count(DISTINCT f."bucket") AS "minutes",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_total_1h_key"
  ON "posts_total_1h" ("bucket") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_total_6h" AS
SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       count(DISTINCT f."bucket") AS "minutes",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_total_6h_key"
  ON "posts_total_6h" ("bucket") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "posts_total_1d" AS
SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       count(DISTINCT f."bucket") AS "minutes",
       sum(f."posts")::bigint AS "posts"
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "posts_total_1d_key"
  ON "posts_total_1d" ("bucket") NULLS NOT DISTINCT;

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_by_lang_5m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_by_lang_5m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_by_lang_5m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_by_lang_5m" ("bucket", "lang", "posts")
  SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
  FROM "posts_per_minute_by_lang" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '5 minutes'
  GROUP BY 1, 2
  ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_5m_ins"
  AFTER INSERT ON "posts_per_minute_by_lang"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_5m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_5m_upd"
  AFTER UPDATE ON "posts_per_minute_by_lang"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_5m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_by_lang_15m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_by_lang_15m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_by_lang_15m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_by_lang_15m" ("bucket", "lang", "posts")
  SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
  FROM "posts_by_lang_5m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '15 minutes'
  GROUP BY 1, 2
  ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_15m_ins"
  AFTER INSERT ON "posts_by_lang_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_15m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_15m_upd"
  AFTER UPDATE ON "posts_by_lang_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_15m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_by_lang_1h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_by_lang_1h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_by_lang_1h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_by_lang_1h" ("bucket", "lang", "posts")
  SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
  FROM "posts_by_lang_15m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '1 hours'
  GROUP BY 1, 2
  ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_1h_ins"
  AFTER INSERT ON "posts_by_lang_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_1h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_1h_upd"
  AFTER UPDATE ON "posts_by_lang_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_1h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_by_lang_6h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_by_lang_6h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_by_lang_6h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_by_lang_6h" ("bucket", "lang", "posts")
  SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
  FROM "posts_by_lang_1h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '6 hours'
  GROUP BY 1, 2
  ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_6h_ins"
  AFTER INSERT ON "posts_by_lang_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_6h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_6h_upd"
  AFTER UPDATE ON "posts_by_lang_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_6h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_by_lang_1d"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_by_lang_1d needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_by_lang_1d:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_by_lang_1d" ("bucket", "lang", "posts")
  SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
  FROM "posts_by_lang_6h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '24 hours'
  GROUP BY 1, 2
  ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_1d_ins"
  AFTER INSERT ON "posts_by_lang_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_1d"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_by_lang_1d_upd"
  AFTER UPDATE ON "posts_by_lang_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_by_lang_1d"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_total_5m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_total_5m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_total_5m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_total_5m" ("bucket", "minutes", "posts")
  SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), count(DISTINCT f."bucket"), sum(f."posts")::bigint
  FROM "posts_per_minute_by_lang" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '5 minutes'
  GROUP BY 1
  ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_5m_ins"
  AFTER INSERT ON "posts_per_minute_by_lang"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_5m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_5m_upd"
  AFTER UPDATE ON "posts_per_minute_by_lang"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_5m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_total_15m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_total_15m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_total_15m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_total_15m" ("bucket", "minutes", "posts")
  SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), sum(f."minutes")::bigint, sum(f."posts")::bigint
  FROM "posts_total_5m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '15 minutes'
  GROUP BY 1
  ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_15m_ins"
  AFTER INSERT ON "posts_total_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_15m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_15m_upd"
  AFTER UPDATE ON "posts_total_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_15m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_total_1h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_total_1h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_total_1h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_total_1h" ("bucket", "minutes", "posts")
  SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), sum(f."minutes")::bigint, sum(f."posts")::bigint
  FROM "posts_total_15m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '1 hours'
  GROUP BY 1
  ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_1h_ins"
  AFTER INSERT ON "posts_total_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_1h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_1h_upd"
  AFTER UPDATE ON "posts_total_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_1h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_total_6h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_total_6h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_total_6h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_total_6h" ("bucket", "minutes", "posts")
  SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), sum(f."minutes")::bigint, sum(f."posts")::bigint
  FROM "posts_total_1h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '6 hours'
  GROUP BY 1
  ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_6h_ins"
  AFTER INSERT ON "posts_total_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_6h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_6h_upd"
  AFTER UPDATE ON "posts_total_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_6h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_posts_total_1d"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup posts_total_1d needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:posts', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('posts_total_1d:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "posts_total_1d" ("bucket", "minutes", "posts")
  SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), sum(f."minutes")::bigint, sum(f."posts")::bigint
  FROM "posts_total_6h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '24 hours'
  GROUP BY 1
  ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_1d_ins"
  AFTER INSERT ON "posts_total_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_1d"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_posts_total_1d_upd"
  AFTER UPDATE ON "posts_total_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_posts_total_1d"();

-- Backfill the grains built from the source. Their inserts fire the triggers,
-- which fill every coarser grain once.
SET LOCAL sqlflow.rollup_backfill = on;
INSERT INTO "posts_by_lang_5m" ("bucket", "lang", "posts")
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."lang", sum(f."posts")::bigint
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1, 2
ON CONFLICT ("bucket", "lang") DO UPDATE SET "posts" = excluded."posts";
INSERT INTO "posts_total_5m" ("bucket", "minutes", "posts")
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), count(DISTINCT f."bucket"), sum(f."posts")::bigint
FROM "posts_per_minute_by_lang" AS f
GROUP BY 1
ON CONFLICT ("bucket") DO UPDATE SET "minutes" = excluded."minutes", "posts" = excluded."posts";
SET LOCAL sqlflow.rollup_backfill = off;
