-- Generated by sqlflow rollup ddl. Do not edit: change the rollups file and
-- regenerate. Run it inside one transaction, which a migration runner opens.

-- Rollup metrics, kept from metrics_1m.
-- Blocks the source's writers until commit, so no write lands between the
-- triggers existing and the backfill reading.
LOCK TABLE "metrics_1m" IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE IF NOT EXISTS "metrics_5m" AS
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       f."dimensions_key" AS "dimensions_key",
       sum(f."value_count")::bigint AS "value_count",
       (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1] AS "value_last",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_5m_key"
  ON "metrics_5m" ("bucket", "name", "type", "dimensions_key") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_15m" AS
SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       f."dimensions_key" AS "dimensions_key",
       sum(f."value_count")::bigint AS "value_count",
       (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1] AS "value_last",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_15m_key"
  ON "metrics_15m" ("bucket", "name", "type", "dimensions_key") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_1h" AS
SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       f."dimensions_key" AS "dimensions_key",
       sum(f."value_count")::bigint AS "value_count",
       (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1] AS "value_last",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_1h_key"
  ON "metrics_1h" ("bucket", "name", "type", "dimensions_key") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_6h" AS
SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       f."dimensions_key" AS "dimensions_key",
       sum(f."value_count")::bigint AS "value_count",
       (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1] AS "value_last",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_6h_key"
  ON "metrics_6h" ("bucket", "name", "type", "dimensions_key") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_1d" AS
SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       f."dimensions_key" AS "dimensions_key",
       sum(f."value_count")::bigint AS "value_count",
       (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1] AS "value_last",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_1d_key"
  ON "metrics_1d" ("bucket", "name", "type", "dimensions_key") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_total_5m" AS
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       sum(f."value_count")::bigint AS "value_count",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_total_5m_key"
  ON "metrics_total_5m" ("bucket", "name", "type") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_total_15m" AS
SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       sum(f."value_count")::bigint AS "value_count",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_total_15m_key"
  ON "metrics_total_15m" ("bucket", "name", "type") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_total_1h" AS
SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       sum(f."value_count")::bigint AS "value_count",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_total_1h_key"
  ON "metrics_total_1h" ("bucket", "name", "type") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_total_6h" AS
SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       sum(f."value_count")::bigint AS "value_count",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_total_6h_key"
  ON "metrics_total_6h" ("bucket", "name", "type") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "metrics_total_1d" AS
SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS "bucket",
       f."name" AS "name",
       f."type" AS "type",
       sum(f."value_count")::bigint AS "value_count",
       max(f."value_max") AS "value_max",
       min(f."value_min") AS "value_min",
       sum(f."value_sum")::double precision AS "value_sum"
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS "metrics_total_1d_key"
  ON "metrics_total_1d" ("bucket", "name", "type") NULLS NOT DISTINCT;

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_5m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_5m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_5m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_5m" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_1m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '5 minutes'
  GROUP BY 1, 2, 3, 4
  ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_5m_ins"
  AFTER INSERT ON "metrics_1m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_5m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_5m_upd"
  AFTER UPDATE ON "metrics_1m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_5m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_15m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_15m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_15m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_15m" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_5m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '15 minutes'
  GROUP BY 1, 2, 3, 4
  ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_15m_ins"
  AFTER INSERT ON "metrics_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_15m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_15m_upd"
  AFTER UPDATE ON "metrics_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_15m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_1h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_1h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_1h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_1h" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_15m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '1 hours'
  GROUP BY 1, 2, 3, 4
  ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_1h_ins"
  AFTER INSERT ON "metrics_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_1h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_1h_upd"
  AFTER UPDATE ON "metrics_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_1h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_6h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_6h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_6h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_6h" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_1h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '6 hours'
  GROUP BY 1, 2, 3, 4
  ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_6h_ins"
  AFTER INSERT ON "metrics_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_6h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_6h_upd"
  AFTER UPDATE ON "metrics_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_6h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_1d"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_1d needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_1d:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_1d" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_6h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '24 hours'
  GROUP BY 1, 2, 3, 4
  ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_1d_ins"
  AFTER INSERT ON "metrics_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_1d"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_1d_upd"
  AFTER UPDATE ON "metrics_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_1d"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_total_5m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_total_5m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_total_5m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_total_5m" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_1m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '5 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '5 minutes'
  GROUP BY 1, 2, 3
  ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_5m_ins"
  AFTER INSERT ON "metrics_1m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_5m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_5m_upd"
  AFTER UPDATE ON "metrics_1m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_5m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_total_15m"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_total_15m needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_total_15m:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_total_15m" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '15 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_total_5m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '15 minutes', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '15 minutes'
  GROUP BY 1, 2, 3
  ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_15m_ins"
  AFTER INSERT ON "metrics_total_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_15m"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_15m_upd"
  AFTER UPDATE ON "metrics_total_5m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_15m"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_total_1h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_total_1h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_total_1h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_total_1h" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '1 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_total_15m" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '1 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '1 hours'
  GROUP BY 1, 2, 3
  ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_1h_ins"
  AFTER INSERT ON "metrics_total_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_1h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_1h_upd"
  AFTER UPDATE ON "metrics_total_15m"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_1h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_total_6h"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_total_6h needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_total_6h:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_total_6h" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '6 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_total_1h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '6 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '6 hours'
  GROUP BY 1, 2, 3
  ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_6h_ins"
  AFTER INSERT ON "metrics_total_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_6h"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_6h_upd"
  AFTER UPDATE ON "metrics_total_1h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_6h"();

CREATE OR REPLACE FUNCTION "sqlflow_rollup_metrics_total_1d"() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup metrics_total_1d needs READ COMMITTED, not %', current_setting('transaction_isolation');
  END IF;
  IF current_setting('sqlflow.rollup_backfill', true) IS DISTINCT FROM 'on' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sqlflow_rollup:metrics', 0));
    PERFORM pg_advisory_xact_lock(hashtextextended('metrics_total_1d:' || extract(epoch FROM touched.b)::bigint, 0))
    FROM (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed ORDER BY 1) AS touched;
  END IF;

  INSERT INTO "metrics_total_1d" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
  SELECT date_bin(INTERVAL '24 hours', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
  FROM "metrics_total_6h" AS f
  JOIN (SELECT DISTINCT date_bin(INTERVAL '24 hours', "bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b FROM changed) AS touched
    ON f."bucket" >= touched.b AND f."bucket" < touched.b + INTERVAL '24 hours'
  GROUP BY 1, 2, 3
  ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
  RETURN NULL;
END $fn$;
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_1d_ins"
  AFTER INSERT ON "metrics_total_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_1d"();
CREATE OR REPLACE TRIGGER "sqlflow_rollup_metrics_total_1d_upd"
  AFTER UPDATE ON "metrics_total_6h"
  REFERENCING NEW TABLE AS changed
  FOR EACH STATEMENT EXECUTE FUNCTION "sqlflow_rollup_metrics_total_1d"();

-- Backfill the grains built from the source. Their inserts fire the triggers,
-- which fill every coarser grain once.
SET LOCAL sqlflow.rollup_backfill = on;
INSERT INTO "metrics_5m" ("bucket", "name", "type", "dimensions_key", "value_count", "value_last", "value_max", "value_min", "value_sum")
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", f."dimensions_key", sum(f."value_count")::bigint, (array_agg(f."value_last" ORDER BY (f."value_last" IS NULL), f."bucket" DESC))[1], max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3, 4
ON CONFLICT ("bucket", "name", "type", "dimensions_key") DO UPDATE SET "value_count" = excluded."value_count", "value_last" = excluded."value_last", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
INSERT INTO "metrics_total_5m" ("bucket", "name", "type", "value_count", "value_max", "value_min", "value_sum")
SELECT date_bin(INTERVAL '5 minutes', f."bucket", TIMESTAMPTZ '2000-01-01 00:00:00+00'), f."name", f."type", sum(f."value_count")::bigint, max(f."value_max"), min(f."value_min"), sum(f."value_sum")::double precision
FROM "metrics_1m" AS f
GROUP BY 1, 2, 3
ON CONFLICT ("bucket", "name", "type") DO UPDATE SET "value_count" = excluded."value_count", "value_max" = excluded."value_max", "value_min" = excluded."value_min", "value_sum" = excluded."value_sum";
SET LOCAL sqlflow.rollup_backfill = off;
