pipeline:
  batch_size: {{ SQLFLOW_BATCH_SIZE|default(1000) }}
  on_error:
    policy: {{ SQLFLOW_SOURCE_ERROR_POLICY|default('RAISE') }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - {{ SQLFLOW_INPUT_TOPIC|default('input-simple-agg-mem') }}

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        properties.city as city,
        count(*) as city_count
      FROM batch
      GROUP BY
        city
      ORDER BY city DESC

  sink:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      topic: {{ SQLFLOW_OUTPUT_TOPIC|default('output-simple-agg-mem') }}