kafka:
  brokers: [localhost:9092]
  group_id: test
  auto_offset_reset: earliest

pipeline:
  type: 'handlers.InferredDiskBatch'

  input:
    batch_size: 1000
    topics:
    - "topic-simple-agg"

  sql: |
    SELECT
      properties.city as city,
      count(*) as city_count
    FROM batch
    GROUP BY
      city
    ORDER BY city DESC

  output:
    type: kafka
    topic: output-1