pipeline:
  batch_size: {{ SQLFLOW_BATCH_SIZE|default:500 }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default:'localhost:9092' }}]
      group_id: {{ SQLFLOW_GROUP_ID|default:'benchmark-inferred' }}
      auto_offset_reset: earliest
      topics:
        - "{{ SQLFLOW_TOPIC|default:'benchmark-input' }}"

  handler:
    type: "handlers.InferredMemBatch"
    sql: |
      SELECT
        properties.city as city,
        COUNT(*) as count
      FROM batch
      GROUP BY properties.city;

  sink:
    type: noop
