commands:
  - name: register locations CSV view
    sql: |
      CREATE VIEW locations AS
        SELECT 
          *
        FROM read_csv_auto('{{ STATIC_ROOT }}/fixtures/locations.csv', header=True);

pipeline:
  batch_size: 1000

  source:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-csv-mem-join"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        properties.city,
        state_full
      FROM batch
      LEFT JOIN (
        SELECT *
          FROM locations
          WHERE locations.city = properties.city 
        LIMIT 1 
      ) AS single_location ON single_location.city = properties.city;

  sink:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      topic: output-csv-mem-join
