tables:
  csv:
    - name: locations
      path: '{{ STATIC_ROOT }}/fixtures/locations.csv'
      # delimiter:
      header: True
      # columns:
      auto_detect: True


pipeline:
  batch_size: 1000

  source:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-csv-mem-join"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        properties.city,
        state_full
      FROM batch
      LEFT JOIN (
        SELECT *
          FROM locations
          WHERE locations.city = properties.city 
        LIMIT 1 
      ) AS single_location ON single_location.city = properties.city;

  sink:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      topic: output-csv-mem-join
