kafka:
  brokers: [localhost:9092]
  group_id: test
  auto_offset_reset: earliest

pipeline:
  input:
    batch_size: 1000
    topics:
    - "topic-1"

  sql: |
    SELECT
      state,
      count(*) as city_count
    FROM batch
    JOIN read_csv('{{ STATIC_ROOT }}/fixtures/locations.csv', auto_detect=True, header=True) as locations ON
    (
      locations.city = properties.city 
    )
    GROUP BY
      state

  output:
    type: kafka
    topic: output-1