tables:
  csv:
    - name: locations
      path: '{{ STATIC_ROOT }}/fixtures/locations.csv'
      # delimiter:
      header: True
      # columns:
      auto_detect: True


pipeline:
  batch_size: 1000

  source:
    type: kafka
    kafka:
      brokers: [localhost:9092]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-csv-mem-join"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        state_full,
        count(*) as city_count
      FROM batch
      JOIN locations ON
      (
        locations.city = properties.city 
      )
      GROUP BY
        state_full
      ORDER BY state_full DESC

  sink:
    type: kafka
    kafka:
      brokers: [localhost:9092]
      topic: output-csv-mem-join
