pipeline:
  batch_size: 1000

  source:
    type: kafka
    kafka:
      brokers: [localhost:9092]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-enrich"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        *,
        {'something': properties.city} as nested_city,
        'extra' as extra
      FROM batch
      
  sink:
    type: kafka
    kafka:
      brokers: [localhost:9092]
      topic: output-enrich
