pipeline:
  batch_size: 1000
  flush_interval_seconds: 30

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      group_id: {{ SQLFLOW_GROUP_ID|default('test') }}
      auto_offset_reset: earliest
      topics:
        - {{ SQLFLOW_INPUT_TOPIC|default('topic-enrich') }}

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        *,
        {'something': properties.city} as nested_city,
        'extra' as extra
      FROM batch
      
  sink:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      topic: {{ SQLFLOW_OUTPUT_TOPIC|default('output-enrich') }}
