commands:
  - name: attach to motherduck
    sql: |
      ATTACH 'md:my_db'

pipeline:
  name: github-motherduck-sink
  description: "Sinks data from github webhooks to motherduck"
  batch_size: {{ SQLFLOW_BATCH_SIZE|default(1) }}

  source:
    type: webhook
    webhook:
      signature_type: 'hmac'
      hmac:
        # X-Hub-Signature-256: sha256=<hex_digest>
        header: 'X-Hub-Signature-256'
        sig_key: 'sha256' # sha256=
        # ? add support for timing

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      INSERT INTO my_db.issues
      SELECT
        action,
        issue ->> 'id' AS issue_id,
        issue ->> 'title' AS issue_title,
        issue ->> 'number' AS issue_number,
        issue ->> 'user' ->> 'login' AS issue_user_login,
        repository ->> 'name' AS repo_name,
        repository ->> 'id' AS repo_id
      FROM batch;

  sink:
    type: noop