commands:
  - name: create source buffer table
    sql: |
      CREATE TABLE source (
            event STRING,
            properties STRUCT(city TEXT),
            user STRUCT(id TEXT)
      );

pipeline:
  batch_size: {{ SQLFLOW_BATCH_SIZE|default:500 }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default:'localhost:9092' }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "input-structured-mem-2"

  handler:
    type: "handlers.StructuredBatch"
    # This is the name of the table that source data will be written to
    table: source
    sql: |
      SELECT 
        properties.city as city,
        COUNT(*) as count 
      FROM source 
      GROUP BY properties.city;

  sink:
    type: console