pipeline:
  batch_size: {{ SQLFLOW_BATCH_SIZE|default(1000) }}
  on_error:
    policy: {{ SQLFLOW_SOURCE_ERROR_POLICY|default('dlq') }}
    dlq:
      type: kafka
      kafka:
        brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
        topic: {{ SQLFLOW_DLQ_TOPIC|default('dlq-topic') }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - {{ SQLFLOW_INPUT_TOPIC|default('input-simple-agg-mem') }}

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        broken
      FROM batch

  sink:
    type: console
