commands:
  - name: attach to motherduck
    sql: |
      ATTACH 'md:my_db'

pipeline:
  name: kafka-motherduck-sink
  description: "Sinks data from kafka to motherduck"
  batch_size: {{ SQLFLOW_BATCH_SIZE|default(1000) }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      group_id: motherduck-sink-1
      auto_offset_reset: earliest
      topics:
        - "input-user-clicks-motherduck"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      INSERT INTO my_db.issues
      SELECT
        action,
        issue ->> 'id' AS issue_id,
        issue ->> 'title' AS issue_title,
        issue ->> 'number' AS issue_number,
        issue ->> 'user' ->> 'login' AS issue_user_login,
        issue ->> 'repository' ->> 'name' AS issue_repo_name,
        issue ->> 'repository' ->> 'id' AS issue_repo_id
      FROM batch;

  sink:
    type: noop
