pipeline:
  batch_size: {{ batch_size|default(5000) }}

  source:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-local-parquet-sink"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT COUNT(*) as num_records FROM batch

  sink:
    type: local
    format:
      type: parquet
    local:
      base_path: {{ sink_base_path|default('/tmp/sqlflow/test/local.parquet.sink.yml') }}
      prefix: testing
