pipeline:
  batch_size: {{ batch_size|default(5000) }}

  source:
    type: kafka
    kafka:
      brokers: [{{ kafka_brokers|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-local-parquet-sink"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT COUNT(*) as num_records FROM batch

  sink:
    type: sqlcommand
    sqlcommand:
      substitutions:
        - var: $sqlflow_uuid
          type: uuid4
      sql: |
        COPY sqlflow_sink_batch
          TO '{{ sink_base_path|default('/tmp/sqlflow/test/local.parquet.sink.yml/testing') }}/$sqlflow_uuid.parquet'
        (FORMAT 'parquet');
