commands:
  - name: Install Extensions
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
  - name: Configure s3
    sql: |
      SET s3_region='{{ SQLFLOW_S3_REGION|default('us-east-1') }}';
      SET s3_url_style='path';
      SET s3_endpoint='localhost:9000';
      SET s3_access_key_id='{{ SQLFLOW_S3_ACCESS_KEY_ID|default('minioadmin') }}';
      SET s3_secret_access_key='{{ SQLFLOW_S3_SECRET_ACCESS_KEY|default('minioadmin') }}';
      SET s3_use_ssl=false;

pipeline:
  batch_size: {{ SQLFLOW_BATCH_SIZE|default(1) }}

  source:
    type: kafka
    kafka:
      brokers: [{{ SQLFLOW_KAFKA_BROKERS|default('localhost:9092') }}]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "input-s3-parquet-sink"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT 
        CAST(timestamp as TIMESTAMP) as timestamp,
        user_id,
        action,
        browser
      FROM batch  

  sink:
    type: sqlcommand
    sqlcommand:
      substitutions:
        - var: $sqlflow_uuid
          type: uuid4
      sql: |
        COPY sqlflow_sink_batch
          TO '{{ SQLFLOW_SINK_BASEPATH }}/$sqlflow_uuid.parquet'
        (FORMAT 'parquet');