kafka:
  brokers: [{{ kafka_brokers|default('localhost:9092') }}]
  group_id: test
  auto_offset_reset: earliest

tables:
  sql:
    - name: agg_cities_count
      sql: |
        CREATE TABLE agg_cities_count (
          timestamp TIMESTAMPTZ,
          city VARCHAR,
          count INT 
        );
        CREATE UNIQUE INDEX daily_cities_count_idx ON agg_cities_count (timestamp, city);

      # tables can be managed as a windowed table.
      # windowed tables flush the table at certain durations.
      manager:
        tumbling_window:
          duration_seconds: 10
          time_field: timestamp

        output:
          type: kafka
          topic: output-tumbling-window-1

pipeline:
  type: 'handlers.InferredMemBatch'

  input:
    batch_size: 1000
    topics: [{{ topic|default('tumbling-window') }}]

  sql: |
    INSERT INTO agg_cities_count
    BY NAME
    SELECT 
      timestamp::date as timestamp,
      properties.city as city,
      count(*) as count
    FROM batch
    GROUP BY 
      timestamp, city
    ON CONFLICT (timestamp, city) 
    DO UPDATE SET count = count + EXCLUDED.count
