# Consumes the bluesky firehose
pipeline:
  batch_size: 100
  source:
    type: websocket
    websocket:
      uri: 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post'

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        strftime(to_timestamp(time_us / 1000000), '%Y-%m-%dT%H:%M:%S') as time,
        kind
      FROM batch

  sink:
    type: console