# Consumes the bluesky firehose
pipeline:
  batch_size: 100
  source:
    type: websocket
    websocket:
      uri: 'wss://jetstream2.us-east.bsky.network/subscribe?wantedCollections=app.bsky.feed.post'

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        epoch_ms(time_us) as time,
        kind
      FROM batch

  sink:
    type: console

#
#    type: kafka
#    kafka:
#      brokers: [localhost:9092]
#      topic: output-bluesky-firehose


