package rollup

import (
	"fmt"
	"strings"

	"github.com/turbolytics/sql-flow/internal/config"
	"github.com/turbolytics/sql-flow/internal/errs"
)

// maxIdentifier is Postgres's identifier limit in bytes. A longer name is
// truncated silently, and two long names could truncate to one.
const maxIdentifier = 63

const ddlHeader = `-- Generated by sqlflow rollup ddl. Do not edit: change the rollups file and
-- regenerate. Run it inside one transaction, which a migration runner opens.
`

// PostgresDDL writes the migration for every rollup in conf: its tables, the
// functions and triggers that keep them current, and the backfill. It
// connects to nothing, and refuses a file that breaks a rule.
func PostgresDDL(conf *config.RollupsConf) (string, error) {
	if err := conf.CheckError(); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(ddlHeader)
	for _, r := range conf.Rollups {
		if err := writePostgresRollup(&b, r); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

// PostgresObjects writes one rollup's tables, unique indexes, functions and
// triggers: what `sqlflow rollup install` applies. The script takes no lock
// of its own and fills nothing: Install locks the source first, in the
// writers' order, and `run` fills in chunks instead of in the migration's
// one transaction.
func PostgresObjects(r config.Rollup) (string, error) {
	if err := checkNames(r); err != nil {
		return "", err
	}
	var b strings.Builder
	writeObjects(&b, r)
	return b.String(), nil
}

func writePostgresRollup(b *strings.Builder, r config.Rollup) error {
	if err := checkNames(r); err != nil {
		return err
	}

	fmt.Fprintf(b, "\n-- Rollup %s, kept from %s.\n", r.Name, r.Source.Table)
	b.WriteString("-- Blocks the source's writers until commit, so no write lands between the\n" +
		"-- triggers existing and the backfill reading.\n")
	fmt.Fprintf(b, "LOCK TABLE %s IN SHARE ROW EXCLUSIVE MODE;\n", quote(r.Source.Table))

	writeObjects(b, r)

	b.WriteString("\n-- Backfill the grains built from the source. Their inserts fire the triggers,\n" +
		"-- which fill every coarser grain once.\n")
	b.WriteString("SET LOCAL sqlflow.rollup_backfill = on;\n")
	for _, set := range r.DimensionSets {
		for _, g := range r.Ladder() {
			if g.From == r.Source.Grain {
				writeUpsert(b, r, set, g, r.Source.Table, "")
			}
		}
	}
	b.WriteString("SET LOCAL sqlflow.rollup_backfill = off;\n")
	return nil
}

// checkNames refuses a generated name Postgres would truncate. Two long
// names could truncate to one, and the second object would replace the
// first.
func checkNames(r config.Rollup) error {
	for _, set := range r.DimensionSets {
		for _, g := range r.Ladder() {
			name := "sqlflow_rollup_" + Table(set, g.Name) + "_ins"
			if len(name) > maxIdentifier {
				return errs.New(errs.CodeConfigRollup,
					"rollup %s: generated name %s is %d bytes, and Postgres truncates names past %d; shorten dimension set %s",
					r.Name, name, len(name), maxIdentifier, set.Name)
			}
		}
	}
	return nil
}

// writeObjects writes every table first, then every function and trigger, so
// no trigger names a table that does not exist yet.
func writeObjects(b *strings.Builder, r config.Rollup) {
	ladder := r.Ladder()
	for _, set := range r.DimensionSets {
		for _, g := range ladder {
			writeTable(b, r, set, g)
		}
	}
	for _, set := range r.DimensionSets {
		for _, g := range ladder {
			writeTrigger(b, r, set, g)
		}
	}
}

// tableQuery is the query that fills a table of set at grain g from the
// source. CREATE TABLE ... AS takes every column's type from it, so the
// generator never connects to learn them, and install builds the expected
// shape of an existing table the same way.
func tableQuery(r config.Rollup, set config.RollupDimensionSet, g config.RollupLevel) string {
	sourceGrain := config.RollupLevel{Name: g.Name, Width: g.Width, From: r.Source.Grain}
	cols := selectList(r, set, sourceGrain)
	names := append(keyColumns(r, set), set.MeasureNames()...)
	for i := range cols {
		cols[i] += " AS " + quote(names[i])
	}
	return fmt.Sprintf("SELECT %s\nFROM %s AS f\nGROUP BY %s",
		strings.Join(cols, ",\n       "), quote(r.Source.Table), groupBy(len(set.Dimensions)+1))
}

// writeTable creates a table from the query that fills it, so every column
// takes its type from the source without the generator connecting.
func writeTable(b *strings.Builder, r config.Rollup, set config.RollupDimensionSet, g config.RollupLevel) {
	table := Table(set, g.Name)
	fmt.Fprintf(b, "\nCREATE TABLE IF NOT EXISTS %s AS\n%s\nWITH NO DATA;\n", quote(table), tableQuery(r, set, g))
	fmt.Fprintf(b, "CREATE UNIQUE INDEX IF NOT EXISTS %s\n  ON %s (%s) NULLS NOT DISTINCT;\n",
		quote(table+"_key"), quote(table), quoteList(keyColumns(r, set)))
}

// writeUpsert writes the INSERT … SELECT … ON CONFLICT that fills a table from
// finer. join is empty for the backfill, which reads every row, and a JOIN
// clause for a trigger, which reads only the touched buckets.
func writeUpsert(b *strings.Builder, r config.Rollup, set config.RollupDimensionSet, g config.RollupLevel, finer, join string) {
	table := Table(set, g.Name)
	keys := keyColumns(r, set)
	measures := set.MeasureNames()
	updates := make([]string, len(measures))
	for i, m := range measures {
		updates[i] = quote(m) + " = excluded." + quote(m)
	}
	fmt.Fprintf(b, "INSERT INTO %s (%s)\nSELECT %s\nFROM %s AS f%s\nGROUP BY %s\nON CONFLICT (%s) DO UPDATE SET %s;\n",
		quote(table), quoteList(append(append([]string{}, keys...), measures...)),
		strings.Join(selectList(r, set, g), ", "), quote(finer), join,
		groupBy(len(keys)), quoteList(keys), strings.Join(updates, ", "))
}

// writeTrigger writes the function that re-merges the buckets a statement on
// the finer table touched, and the INSERT and UPDATE triggers that call it.
// Two triggers, because Postgres refuses a transition table on a trigger with
// more than one event. An upsert fires both, each with its own rows.
func writeTrigger(b *strings.Builder, r config.Rollup, set config.RollupDimensionSet, g config.RollupLevel) {
	table := Table(set, g.Name)
	fn := "sqlflow_rollup_" + table
	finer := r.Source.Table
	if g.From != r.Source.Grain {
		finer = Table(set, g.From)
	}
	t := quote(r.Source.TimeColumn)
	join := fmt.Sprintf("\nJOIN (SELECT DISTINCT %s AS b FROM changed) AS touched\n  ON f.%s >= touched.b AND f.%s < touched.b + %s",
		bin(g.Width, t), t, t, interval(g.Width))

	var upsert strings.Builder
	writeUpsert(&upsert, r, set, g, finer, join)

	fmt.Fprintf(b, `
CREATE OR REPLACE FUNCTION %[1]s() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  -- The lock serializes writers only because each statement in READ COMMITTED
  -- takes a new snapshot, which sees the writer the lock waited on.
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION 'sqlflow rollup %[2]s needs READ COMMITTED, not %%', current_setting('transaction_isolation');
  END IF;
%[3]s
%[4]s
  RETURN NULL;
END $fn$;
`, quote(fn), table, lockSQL(table, g.Width, r.Source.TimeColumn), indent(upsert.String(), "  "))

	for _, ev := range []struct{ suffix, event string }{{"ins", "INSERT"}, {"upd", "UPDATE"}} {
		fmt.Fprintf(b, "CREATE OR REPLACE TRIGGER %s\n  AFTER %s ON %s\n  REFERENCING NEW TABLE AS changed\n  FOR EACH STATEMENT EXECUTE FUNCTION %s();\n",
			quote(fn+"_"+ev.suffix), ev.event, quote(finer), quote(fn))
	}
}

// indent prefixes every non-empty line.
func indent(s, prefix string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = prefix + l
		}
	}
	return strings.Join(lines, "\n")
}
