"""Tests for coverage_matrix.statusfiles."""

import os

from coverage_matrix.registries import (
    LEVELS, PASS, STATUS_DIR, load_features, load_integrations,
    load_invariants)
from coverage_matrix.statusfiles import (
    read_status, render_status_file, status_from_snapshot, write_status)
from samples import *  # noqa: F401,F403


def test_the_integration_and_status_directories_agree():
    """Everything about one integration is two files of the same name: what
    it declares, and where it stands."""
    declared = {i["id"] for i in load_integrations()}
    status = set(read_status(STATUS_DIR)["integrations"])
    assert status <= declared


def test_every_committed_status_row_names_a_declared_id():
    """A row for something the registries no longer declare is a stale file
    write_status should have removed."""
    status = read_status(STATUS_DIR)
    features = {f["id"] for f in load_features()}
    invariants = {i["id"] for i in load_invariants()}
    integrations = {i["id"] for i in load_integrations()}

    assert set(status["features"]) <= features
    assert set(status["integrations"]) <= integrations
    for rows in status["integrations"].values():
        assert set(rows) <= invariants


def test_the_status_projection_keeps_one_status_per_level():
    st = status_of(go_results={"TestSinkClickhouse_A": PASS},
                   go_covers={"TestSinkClickhouse_A": ["sink.clickhouse"]})
    assert st["features"]["sink.clickhouse"] == {
        "unit": "covered", "integration": "not_required", "release": "missing"}


def test_the_status_projection_files_invariants_under_their_integration():
    st = status_of()
    assert st["integrations"]["sink.clickhouse"]["sink.flush.keeps_batch"] == {
        lvl: "missing" for lvl in LEVELS}
    assert "sink.flush.keeps_batch" not in st["integrations"].get("source.kafka", {})


def test_an_exempt_row_matches_the_registry():
    """The row repeats what integrations.yml declares, so a reader of one
    file sees the whole picture. The generator writes it from the registry,
    so the two cannot disagree."""
    st = status_of()
    assert st["integrations"]["sink.console"]["sink.flush.keeps_batch"] == {
        lvl: "exempt" for lvl in LEVELS}


def test_a_status_file_is_one_row_per_line_sorted_by_id():
    text = render_status_file(
        {"sink.console": {"unit": "covered", "integration": "not_required",
                          "release": "missing"},
         "cli.version": {"unit": "missing", "integration": "not_required",
                         "release": "covered"}},
        about="feature in ../features.yml")
    assert text.splitlines() == [
        "# Generated by `make coverage-matrix`. Do not edit by hand.",
        "# One line per feature in ../features.yml, sorted by id: the status of each level.",
        "cli.version: {unit: missing, integration: not_required, release: covered}",
        "sink.console: {unit: covered, integration: not_required, release: missing}",
    ]


def test_write_status_then_read_status_round_trips(tmp_path):
    st = status_of(go_results={"TestSinkClickhouse_A": PASS},
                   go_covers={"TestSinkClickhouse_A": ["sink.clickhouse"]})
    written = write_status(st, str(tmp_path))

    assert written == ["features.yml", "sink.clickhouse.yml", "sink.console.yml",
                       "source.kafka.yml"]
    assert read_status(str(tmp_path)) == st


def test_write_status_removes_a_file_for_an_integration_that_is_gone(tmp_path):
    (tmp_path / "sink.retired.yml").write_text("x: {unit: covered}\n")
    write_status(status_of(), str(tmp_path))
    assert not (tmp_path / "sink.retired.yml").exists()


def test_write_status_removes_only_yml_files(tmp_path):
    """Only .yml files are the generator's to remove."""
    (tmp_path / "README.md").write_text("keep\n")
    write_status(status_of(), str(tmp_path))
    assert (tmp_path / "README.md").read_text() == "keep\n"


def test_read_status_of_an_absent_directory_is_empty(tmp_path):
    assert read_status(str(tmp_path / "nope")) == {"features": {}, "integrations": {}}


def test_adding_a_test_to_a_covered_feature_changes_no_status_file(tmp_path):
    """The point of the change: a PR that adds tests inside covered features
    must produce no diff under docs/coverage."""
    before = tmp_path / "before"
    after = tmp_path / "after"
    write_status(status_of(
        go_results={"TestSinkClickhouse_A": PASS},
        go_covers={"TestSinkClickhouse_A": ["sink.clickhouse"]}), str(before))
    write_status(status_of(
        go_results={"TestSinkClickhouse_A": PASS, "TestSinkClickhouse_B": PASS},
        go_covers={"TestSinkClickhouse_A": ["sink.clickhouse"],
                   "TestSinkClickhouse_B": ["sink.clickhouse"]}), str(after))

    for name in sorted(os.listdir(before)):
        assert (before / name).read_bytes() == (after / name).read_bytes(), name


def test_a_status_flip_changes_one_line_in_one_file(tmp_path):
    before = tmp_path / "before"
    after = tmp_path / "after"
    write_status(status_of(), str(before))
    write_status(status_of(
        go_results={"TestSinkClickhouse_A": PASS},
        go_covers={"TestSinkClickhouse_A": ["sink.clickhouse"]}), str(after))

    changed = {}
    for name in sorted(os.listdir(before)):
        a = (before / name).read_text().splitlines()
        b = (after / name).read_text().splitlines()
        diff = [i for i, (x, y) in enumerate(zip(a, b)) if x != y]
        if diff or len(a) != len(b):
            changed[name] = diff
    assert list(changed) == ["features.yml"]
    assert len(changed["features.yml"]) == 1


def test_an_unattributed_test_reaches_no_status_file(tmp_path):
    write_status(status_of(go_results={"TestNobodyDeclaredThis": PASS}),
                    str(tmp_path))
    for name in os.listdir(tmp_path):
        assert "TestNobodyDeclaredThis" not in (tmp_path / name).read_text()


def test_the_page_snapshot_reaches_the_same_gaps_as_the_full_snapshot():
    required = [dict(INVARIANTS[0], requires=["unit"], enforced=True)]
    full = snap()
    full.update(inv_snap(invariants=required))
    ps = page_of(status=status_from_snapshot(full), invariants=required)

    assert ps["gaps"] == full["gaps"]
    assert ps["invariant_gaps"] == full["invariant_gaps"]