"""The published detail: counts and names, never committed.

Every line here changes when a test is added, which is why it left the
page. CI appends it to the job summary and uploads it on every run.
"""

from .invariants import cell_state
from .registries import LEVELS


def render_report(snap):
    """Everything the page dropped: counts, names, secondary attribution,
    unattributed tests, unknown markers.

    Not committed. Every line here changes when a test is added, which is
    exactly why it left the page. CI appends it to the job summary and uploads
    it on every run, and `make coverage-check` prints it.
    """
    lines = [
        "# Coverage report",
        "",
        "Generated by `make coverage-check` from the suite reports, and published",
        "by CI on every run. Not committed: every line here changes when a test",
        "is added, and `docs/coverage/matrix.md` changes only when a status does.",
        "`.coverage/matrix.json` names every test behind every count.",
        "",
        "| Feature | " + " | ".join(LEVELS) + " | Tests |",
        "| --- | " + " | ".join("---" for _ in LEVELS) + " | --- |",
    ]
    for feature in snap["features"]:
        counts = [len(feature["levels"][lvl].get("tests", [])) for lvl in LEVELS]
        cells = " | ".join(str(c) if c else "—" for c in counts)
        lines.append(f"| `{feature['id']}` | {cells} | {sum(counts) or '—'} |")
    lines.append("")

    if snap.get("invariants"):
        argument = strongest_argument(snap)
        if argument:
            feature, tests, invariant, proven, applicable = argument
            lines += [
                "## Why invariants, and not the test count",
                "",
                f"`{feature}` carries {tests} attributed tests, more than anything",
                f"else in the `{domain(feature)}` layer. `{invariant}`, an invariant",
                f"of that same layer, is proven on {proven} of the {applicable}",
                "integrations it applies to.",
                "",
                "Those two numbers are the argument. Tests accumulate around the",
                "code that was written; an invariant is the claim that code exists",
                "to uphold. A suite can exercise a retry ladder in every direction",
                "and never ask whether the sink underneath keeps the rows the",
                "ladder re-sends -- and if it does not, every one of those tests",
                "passes while the pipeline loses data. The feature table calls that",
                "covered. This one does not.",
                "",
            ]

    # Secondary attribution is visible on purpose. One test per feature is the
    # goal; a feature every test claims second is one no test is about, and
    # this is where that shows.
    by_marker = []
    for feature in snap["features"]:
        for level in LEVELS:
            cell = feature["levels"][level]
            tests = cell.get("tests", [])
            if tests and len(cell.get("by_marker", [])) == len(tests):
                by_marker.append((feature["id"], level, tests))
    if by_marker:
        lines += [
            "## Covered only by another test's marker",
            "",
            "Every test that covers these claims something else first. That is",
            "legitimate for a capability an end-to-end run proves in passing, and",
            "a smell for one that deserves a test of its own.",
            "",
        ]
        for fid, level, names in by_marker:
            lines.append(f"- `{fid}` ({level}) — via {', '.join(f'`{n}`' for n in names)}")
        lines.append("")

    for level in LEVELS:
        names = snap.get("unattributed", {}).get(level, [])
        if names:
            lines += [
                f"## Unattributed {level} tests ({len(names)})",
                "",
                "These carry no `coverage.Covers` marker, so they cover nothing.",
                "Add the marker, or add the feature to `features.yml` first.",
                "",
            ]
            lines += [f"- `{n}`" for n in names]
            lines.append("")

    unknown = snap.get("unknown_markers", [])
    unknown_invariants = snap.get("unknown_invariant_markers", [])
    if unknown or unknown_invariants:
        lines += [
            "## Markers naming an unknown feature, invariant, or integration",
            "",
            "These fail `make coverage-check`. A marker that names nothing the",
            "registries declare is a typo, and crediting it would invent a cell.",
            "",
        ]
        for entry in unknown:
            lines.append(f"- `{entry['test']}` marks `{entry['feature']}`")
        for entry in unknown_invariants:
            lines.append(f"- `{entry['test']}` marks `{entry['invariant']}` "
                         f"on `{entry['integration']}`")
        lines.append("")

    return "\n".join(lines) + "\n"


def domain(identifier):
    """sink.retry -> sink. The subsystem a feature or invariant belongs to."""
    return identifier.split(".", 1)[0]


def most_tested_feature(snap, within=None):
    """The feature carrying the most attributed tests, and how many.

    `within` restricts to one subsystem. Counted over features rather than
    integrations because the sharpest case is a cross-cutting one: sink.retry
    is not a sink anyone configures, and it accumulated more tests than any
    other part of the sink layer.
    """
    best = None
    for feature in snap["features"]:
        if within and domain(feature["id"]) != within:
            continue
        total = sum(len(feature["levels"][lvl].get("tests", [])) for lvl in LEVELS)
        if best is None or total > best[1]:
            best = (feature["id"], total)
    return best


def least_proven_invariant(snap, within=None):
    """The invariant proven on the fewest of the integrations it applies to.

    Exempt cells count as neither proof nor hole: an integration excused from
    an invariant is not evidence that the invariant is unproven.
    """
    worst = None
    for inv in snap["invariants"]:
        if within and domain(inv["id"]) != within:
            continue
        applicable = [levels for levels in inv["integrations"].values()
                      if cell_state(levels) != "exempt"]
        if not applicable:
            continue
        proven = sum(1 for levels in applicable if cell_state(levels) == "covered")
        share = proven / len(applicable)
        if worst is None or share < worst[3]:
            worst = (inv["id"], proven, len(applicable), share)
    return worst


def strongest_argument(snap):
    """A heavily tested feature paired with an unproven invariant of the same
    subsystem, as (feature, tests, invariant, proven, applicable).

    Same subsystem is what makes the pair an argument rather than a
    coincidence. A feature with many tests somewhere else in the engine says
    nothing about a sink invariant; a feature with many tests *in the sink
    layer* alongside a sink invariant nothing proves says exactly the thing
    this file exists to say.

    Generated rather than written down so it cannot go stale.
    """
    best = None
    for subsystem in sorted({domain(i["id"]) for i in snap["invariants"]}):
        feature = most_tested_feature(snap, within=subsystem)
        invariant = least_proven_invariant(snap, within=subsystem)
        if not feature or not invariant or feature[1] == 0:
            continue
        # Rank by tests: the more a subsystem is tested while an invariant of
        # its own goes unproven, the louder the point.
        if best is None or feature[1] > best[1]:
            best = (feature[0], feature[1], invariant[0], invariant[1], invariant[2])
    return best
