"""The committed artifact: one status per cell, one file per integration.

Nothing here carries a test name. That is the point: a test added inside
a covered feature changes no committed file, so it cannot go stale and
cannot conflict.
"""

import os

import yaml

from .registries import LEVELS


STATUS_HEADER = "# Generated by `make coverage-matrix`. Do not edit by hand."


def status_from_snapshot(snap):
    """The statuses the gate judges, and nothing else.

    features:     {feature: {level: status}}
    integrations: {integration: {invariant: {level: status}}}

    An integration with no applicable invariant does not appear, so it gets
    no file. An exempt cell appears as exempt at every level: the row repeats
    what the registry declares, so a reader of one file sees the whole
    picture for that integration.
    """
    features = {
        f["id"]: {lvl: f["levels"][lvl]["status"] for lvl in LEVELS}
        for f in snap["features"]
    }
    integrations = {}
    for inv in snap.get("invariants", []):
        for iid, levels in inv["integrations"].items():
            integrations.setdefault(iid, {})[inv["id"]] = {
                lvl: levels[lvl]["status"] for lvl in LEVELS}
    return {"features": features, "integrations": integrations}


def render_status_file(rows, about):
    """One row per line, sorted by id, levels in a flow mapping.

    Written by hand rather than by yaml.dump: git merges lines, so one fact
    per line is what lets two branches that flip different rows merge
    cleanly, and yaml.dump spreads a row over four.
    """
    lines = [
        STATUS_HEADER,
        f"# One line per {about}, sorted by id: the status of each level.",
    ]
    for rid in sorted(rows):
        levels = ", ".join(f"{lvl}: {rows[rid][lvl]}" for lvl in LEVELS)
        lines.append(f"{rid}: {{{levels}}}")
    return "\n".join(lines) + "\n"


def write_status(status, directory):
    """Write the status directory and remove any .yml it no longer owns.

    A file for an integration the registry dropped would otherwise survive
    as a stale row nothing regenerates. Only .yml files are removed; anything
    else in the directory is not the generator's.
    """
    os.makedirs(directory, exist_ok=True)
    files = {"features.yml": render_status_file(
        status["features"], "feature in ../features.yml")}
    for iid, rows in status["integrations"].items():
        files[f"{iid}.yml"] = render_status_file(
            rows, f"invariant that applies to {iid}")

    for name in os.listdir(directory):
        if name.endswith(".yml") and name not in files:
            os.remove(os.path.join(directory, name))
    for name, text in files.items():
        with open(os.path.join(directory, name), "w") as fh:
            fh.write(text)
    return sorted(files)


def read_status(directory):
    """The inverse of write_status. An absent directory reads as empty, so
    the page renders (as all missing) before the first generation."""
    status = {"features": {}, "integrations": {}}
    if not os.path.isdir(directory):
        return status
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".yml"):
            continue
        with open(os.path.join(directory, name)) as fh:
            rows = yaml.safe_load(fh) or {}
        if name == "features.yml":
            status["features"] = rows
        else:
            status["integrations"][name[:-len(".yml")]] = rows
    return status
