"""The Arrow type lattice, and the integration page it publishes.

The lattice is closed, so a key outside it is a typo and a key inside it
that a sink does not declare is a gap. Both are reported rather than
rendered as a missing cell.
"""

from .registries import OUTCOMES


def render_types_page(lattice, integration):
    """The type mapping table, as the ClickHouse integration page publishes it.

    Keyed by DuckDB SQL type rather than by Arrow type, because a user writes a
    CAST and never sees an Arrow type. The Arrow key is the join and stays out
    of the output.

    Generated from the same declaration the type runner judges, so the page
    cannot claim something no test proved. That is the point: every row of the
    hand-written table it replaces was measured once, by hand, and nothing held
    it to the sink afterwards, so the first type change would have made the
    page wrong with no test to say so.
    """
    by_key = integration.get("types", {})
    supported, unsupported = [], []

    for entry in lattice:
        decl = by_key.get(entry["key"])
        if not decl:
            continue
        casts = ", ".join("`%s`" % d for d in entry["duckdb"])
        if decl["outcome"] == "unsupported":
            unsupported.append("- %s" % casts)
            continue
        # A column entry, not a name: the value written belongs to the (key,
        # column) pair, and the page publishes the pair's destination type.
        cols = ", ".join("`%s`" % c["type"] for c in decl.get("columns", []))
        supported.append("| %s | %s | %s |" % (casts, cols, decl.get("rule", "")))

    out = [
        "<!-- Generated by scripts/coverage_matrix. Do not edit. -->",
        "<!-- Every row is proven by TestIntegrationSinkClickhouse_Types. -->",
        "",
        "## Type mapping {#type-mapping}",
        "",
        "sqlflow hands each batch to ClickHouse as rows built from the Arrow "
        "table DuckDB produces, so what matters is the type each SQL column "
        "ends up with. Cast in the handler SQL to control it.",
        "",
        "| DuckDB SQL type (cast to) | ClickHouse column types that accept it | Notes |",
        "| --- | --- | --- |",
    ]
    out += supported
    # The null rows are declared separately from the types because the answer
    # belongs to the destination column rather than to any Arrow type, and they
    # are the rows a reader is most likely to be surprised by: nothing raises,
    # and the absence is simply gone.
    nulls = integration.get("nulls", {})
    if nulls.get("default"):
        out.append("| `NULL` in any column | the column's own type | %s |"
                   % nulls["default"].get("rule", ""))
    if nulls.get("list_element"):
        out.append("| `NULL` inside a `LIST` | the element's own type | %s |"
                   % nulls["list_element"].get("rule", ""))

    out += [
        "",
        "Values are matched to columns **by name**, not by position.",
        "",
        "### Unsupported {#unsupported}",
        "",
        "These fail the batch with `user.sink.type_unsupported` rather than "
        "reaching the table. Cast or flatten them in the handler SQL.",
        "",
    ]
    out += unsupported
    out.append("")
    return "\n".join(out)


def validate_types(lattice, integrations):
    """Every problem in a type table, one line each. Empty when consistent.

    The lattice is closed, so a key outside it is a typo and a key inside it
    that a sink does not declare is a gap. Both are reported here rather than
    rendered as a missing cell: "missing" is the signal the matrix exists to
    carry, and it must not be spendable on a misspelling.

    A sink with no type table gets no lines at all. One sink has a table in
    this revision and five do not, and 29 lines each would bury the one that
    does. The absent tables are visible as missing cells, which is the right
    signal for a sink whose type behaviour nobody has written down.
    """
    problems = []
    keys = {entry["key"] for entry in lattice}

    for integ in integrations:
        types = integ.get("types")
        if not types:
            continue

        iid = integ["id"]
        for key, decl in sorted(types.items()):
            if key not in keys:
                problems.append(
                    f"integrations/{iid}.yml: declares type {key!r}, "
                    "which lattice.yml does not list")
                continue

            outcome = decl.get("outcome")
            if outcome not in OUTCOMES:
                problems.append(
                    f"integrations/{iid}.yml: type {key!r} outcome "
                    f"{outcome!r} is not one of {OUTCOMES}")
            # A coercion stated as an outcome and no rule is an excuse. The
            # rule is what the integration page publishes, and what a reader
            # needs to predict what their column will hold.
            if outcome == "coerced" and not decl.get("rule"):
                problems.append(
                    f"integrations/{iid}.yml: type {key!r} is coerced with no rule")
            if outcome == "unsupported" and not decl.get("code"):
                problems.append(
                    f"integrations/{iid}.yml: type {key!r} is unsupported with no code")
            if outcome in ("exact", "coerced") and not decl.get("columns"):
                problems.append(
                    f"integrations/{iid}.yml: type {key!r} is {outcome} but names "
                    "no destination column type to write it to")
            for col in decl.get("columns", []):
                if not col.get("type"):
                    problems.append(
                        f"integrations/{iid}.yml: type {key!r} has a column entry "
                        "with no type")
                if not col.get("expect"):
                    problems.append(
                        f"integrations/{iid}.yml: type {key!r} into "
                        f"{col.get('type')!r} names no expect, so nothing checks "
                        "what the destination holds")
                # Text is the only thing a destination reparses, so a value on
                # any other key would be built and then ignored.
                if col.get("value") and key != "utf8":
                    problems.append(
                        f"integrations/{iid}.yml: type {key!r} into "
                        f"{col.get('type')!r} declares a value, and only utf8 may")

        for key in sorted(keys - set(types)):
            problems.append(
                f"integrations/{iid}.yml: has a type table and declares no "
                f"outcome for {key!r}, which lattice.yml lists")

    return problems
