

kafka:
  brokers: [host.docker.internal:29092]
  group_id: test
  auto_offset_reset: earliest

pipeline:
  input:
    batch_size: 1000
    topics:
    - "topic-local-docker"

  sql: |
    SELECT
      properties.city as city,
      count(*) as city_count
    FROM batch
    GROUP BY
      city

  output:
    type: kafka
    topic: output-1