pipeline:
  batch_size: 1000

  source:
    type: kafka
    kafka:
      brokers: [host.docker.internal:29092]
      group_id: test
      auto_offset_reset: earliest
      topics:
        - "topic-local-docker"

  handler:
    type: 'handlers.InferredMemBatch'
    sql: |
      SELECT
        properties.city as city,
        count(*) as city_count
      FROM batch
      ORDER BY city DESC

  sink:
    type: kafka
    kafka:
      brokers: [host.docker.internal:29092]
      topic: output-local-docker