#!/usr/bin/env python3
"""Build the feature coverage matrix from test suite output.

Two axes, deliberately independent:

  Feature  what sqlflow does, e.g. sink.iceberg. Declared in
           docs/coverage/features.yml. Never encodes a test level.
  Level    where the test ran: `unit` for go test, `release` for the image
           suite. Derived from which file the result came out of, never
           declared, so it cannot drift from reality.

Keeping them separate is what lets the matrix answer the question that went
unanswered for months: which features are covered by a unit test but never
proven against the shipped image.

A skipped test does not cover its feature. It reports as SKIP, because a skip
that reads as coverage is exactly how sink.iceberg shipped untested.

Usage:
    coverage_matrix.py --go go.json --pytest pytest.json --write
    coverage_matrix.py --go go.json --pytest pytest.json --check

`--check` exits non-zero when a feature is missing a level it requires.
"""

import argparse
import json
import os
import re
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(REPO, "docs", "coverage", "features.yml")
MATRIX = os.path.join(REPO, "docs", "coverage", "matrix.md")

PASS, SKIP, FAIL = "pass", "skip", "fail"


def load_features():
    with open(REGISTRY) as fh:
        return yaml.safe_load(fh)["features"]


def go_prefix(feature_id):
    """sink.clickhouse -> TestSinkClickhouse"""
    parts = re.split(r"[._]", feature_id)
    return "Test" + "".join(p.capitalize() for p in parts)


def py_prefix(feature_id):
    """sink.clickhouse -> test_sink_clickhouse"""
    return "test_" + feature_id.replace(".", "_")


def match(name, prefixes):
    """Longest matching prefix wins, so sink.iceberg does not swallow
    sink.iceberg_merge."""
    best = None
    for feature_id, prefix in prefixes.items():
        if name.startswith(prefix):
            if best is None or len(prefix) > len(prefixes[best]):
                best = feature_id
    return best


def parse_go(path):
    """Read `go test -json` output into {test name: outcome}."""
    results = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            name, action = event.get("Test"), event.get("Action")
            if not name:
                continue
            # Subtests report their own outcome; the parent aggregates them.
            if action == "pass":
                results.setdefault(name, PASS)
            elif action == "skip":
                results[name] = SKIP if results.get(name) != PASS else PASS
            elif action == "fail":
                results[name] = FAIL
    return results


def parse_pytest(path):
    """Read a pytest --json-report (or -rA summary) into {test name: outcome}."""
    with open(path) as fh:
        report = json.load(fh)

    results = {}
    for test in report.get("tests", []):
        name = test["nodeid"].rsplit("::", 1)[-1]
        outcome = test.get("outcome")
        results[name] = {
            "passed": PASS, "skipped": SKIP,
        }.get(outcome, FAIL)
    return results


def build(features, go_results, py_results):
    go_prefixes = {f["id"]: go_prefix(f["id"]) for f in features}
    py_prefixes = {f["id"]: py_prefix(f["id"]) for f in features}

    coverage = {f["id"]: {"unit": [], "release": []} for f in features}
    unmatched = {"unit": [], "release": []}

    for name, outcome in sorted(go_results.items()):
        feature_id = match(name, go_prefixes)
        if feature_id:
            coverage[feature_id]["unit"].append((name, outcome))
        else:
            unmatched["unit"].append(name)

    for name, outcome in sorted(py_results.items()):
        feature_id = match(name, py_prefixes)
        if feature_id:
            coverage[feature_id]["release"].append((name, outcome))
        else:
            unmatched["release"].append(name)

    return coverage, unmatched


def status(entries):
    """A level is covered only if something there actually ran and passed."""
    if not entries:
        return "missing"
    if any(o == FAIL for _, o in entries):
        return "failing"
    if all(o == SKIP for _, o in entries):
        return "skipped"
    return "covered"


MARK = {
    "covered": "✅",
    "skipped": "⚠️ skipped",
    "missing": "❌ **missing**",
    "failing": "🔥 failing",
    "n/a": "—",
}


def render(features, coverage, unmatched):
    lines = [
        "# Feature coverage matrix",
        "",
        "Generated by `make coverage-matrix`. Do not edit by hand.",
        "",
        "Features come from `docs/coverage/features.yml`. Levels are derived from",
        "where each test ran, so they cannot drift. A **skipped** test does not",
        "count as coverage: a skip that reads as a pass is how `sink.iceberg`",
        "shipped for months without ever being written to.",
        "",
        "| Feature | What it does | unit | release | Tests |",
        "| --- | --- | --- | --- | --- |",
    ]

    gaps = []
    for feature in features:
        fid = feature["id"]
        required = set(feature.get("requires", []))
        cells = {}
        for level in ("unit", "release"):
            if level not in required and not coverage[fid][level]:
                cells[level] = MARK["n/a"]
                continue
            state = status(coverage[fid][level])
            cells[level] = MARK[state]
            # No baseline and no escape hatch. A gap you can silence by editing
            # a config is not a gap; it fails the build until a test covers it
            # or the registry honestly stops requiring it.
            if level in required and state != "covered":
                gaps.append((fid, level, state))

        names = [n for lvl in ("unit", "release") for n, _ in coverage[fid][lvl]]
        shown = ", ".join(f"`{n}`" for n in names[:3])
        if len(names) > 3:
            shown += f" +{len(names) - 3} more"
        lines.append(
            f"| `{fid}` | {feature['description']} | "
            f"{cells['unit']} | {cells['release']} | {shown or '—'} |"
        )

    lines += ["", f"**{len(features)} features declared.**", ""]

    if gaps:
        lines += ["## Gaps", ""]
        for fid, level, state in gaps:
            lines.append(f"- `{fid}` requires **{level}** coverage and is *{state}*.")
        lines.append("")

    for level in ("unit", "release"):
        if unmatched[level]:
            lines += [
                f"## Unattributed {level} tests ({len(unmatched[level])})",
                "",
                "These do not match any declared feature. Either rename them to the",
                "convention, or add the feature to `features.yml`.",
                "",
            ]
            lines += [f"- `{n}`" for n in unmatched[level]]
            lines.append("")

    return "\n".join(lines) + "\n", gaps


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--go", help="go test -json output")
    ap.add_argument("--pytest", help="pytest --json-report output")
    ap.add_argument("--write", action="store_true", help="write matrix.md")
    ap.add_argument("--check", action="store_true", help="exit non-zero on gaps")
    args = ap.parse_args()

    features = load_features()
    go_results = parse_go(args.go) if args.go and os.path.exists(args.go) else {}
    py_results = parse_pytest(args.pytest) if args.pytest and os.path.exists(args.pytest) else {}

    coverage, unmatched = build(features, go_results, py_results)
    rendered, gaps = render(features, coverage, unmatched)

    if args.write:
        os.makedirs(os.path.dirname(MATRIX), exist_ok=True)
        with open(MATRIX, "w") as fh:
            fh.write(rendered)
        print(f"wrote {os.path.relpath(MATRIX, REPO)}")
    else:
        print(rendered)

    if args.check and gaps:
        print(f"\n{len(gaps)} coverage gap(s):", file=sys.stderr)
        for fid, level, state in gaps:
            print(f"  {fid}: {level} is {state}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
